title = "Разработка интернет сайтов"
baseURL = "https://cosmos-factory.ru"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "Kubar"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Фабрика сайтов для успешного бизнеса"
    author = "Kubar"
    description = "Разработка интерннет сайтов, разработка веб сайтов, разработка сайта компании, разработка web сайтов, разработка веб дизайна сайта, заказать разработку сайта, дизайн лендинга, разработка лендинг пейдж, где можно сделать сайт, заказать сайт ключ, заказать дизайн сайта"
    logoBig = "/images/lo-4.png"
    logoSmall = "/images/lo-4.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/lo-4.png"
    ICQ = "747947807"
    youtube = "UCnhFCr2QiMSCQvPjjLCdE8w?view_as=subscriber"
    vk = "public169335916"
    telegram = "brbnv"
    email = "admin@cosmos-factory.ru"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true
    enableRobotsTXT = true

[[menu.main]]
    name = "О нас"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Работы"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "FAQ"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Спросить"
    url  = "/#contact"
    weight = 4

[blackfriday]
    hrefTargetBlank = true    